server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
spring:
  cloud:
    gateway:
      routes:
      - id: config-client-sample
        uri: lb://config-client-sample/sayHi
        predicates:
        - Path=/config-client-sample/sayHi
      - id: feign-client-sample
        uri: lb://feign-client-sample/hello
        predicates:
        - Path=/feign-client-sample/hello
