server:
  port: 8785
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
spring:
  cloud:
    gateway:
      routes:
      - id: feign-client-sample
        uri: lb://feign-client-sample/feign-client
        predicates:
        - Path=/feign-client/**
        
      - id: config-client-sample
        uri: lb://config-client-sample/config-client
        predicates:
        - Path=/config-client/**
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
